### ISSUE TITLE
shebang 💥 

### ISSUE THREAD

**Issue by zeke** [yoshuawuyts/winstall#1]
```
❯ winstall index.js 
{ Error: Unexpected character '#' (3:0) while parsing /Users/z/Desktop/libcc-check/index.js while parsing file: /Users/z/Desktop/libcc-check/index.js
    at smallError (/usr/local/lib/node_modules/winstall/index.js:30:16)
    at /usr/local/lib/node_modules/winstall/index.js:24:26
    at /usr/local/lib/node_modules/winstall/node_modules/pump/index.js:73:7
    at f (/usr/local/lib/node_modules/winstall/node_modules/once/once.js:25:25)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/winstall/node_modules/pump/index.js:31:5)
    at WriteStream.f (/usr/local/lib/node_modules/winstall/node_modules/once/once.js:25:25)
    at WriteStream.onfinish (/usr/local/lib/node_modules/winstall/node_modules/end-of-stream/index.js:30:27)
    at emitNone (events.js:110:20)
    at WriteStream.emit (events.js:207:7)
    at finishMaybe (_stream_writable.js:587:14)
  index: undefined,
  lineNumber: undefined,
  filename: '/Users/z/Desktop/libcc-check/index.js',
  column: undefined }
```

```
❯ head index.js 
#!/usr/bin/env node

const got = require('got')
require('colors')
```

```
❯ winstall --version
1.0.1
```

**Comment by yoshuawuyts** [comment]
Oh yeah, I believe acorn really dislikes those :( - not sure how to work around it? Perhaps there's a flag in Acorn we can ignore... orrrr... errr...

suggestions welcome!
