### ISSUE TITLE
TypeError: Cannot read property 'main' of undefined

### ISSUE THREAD

**Issue by zeke** [yoshuawuyts/winstall#2]
```
❯ winstall         
/usr/local/lib/node_modules/winstall/node_modules/installify/node_modules/resolve/lib/async.js:91
                        var dir = path.resolve(x, pkg.main);
                                                     ^

TypeError: Cannot read property 'main' of undefined
    at /usr/local/lib/node_modules/winstall/node_modules/installify/node_modules/resolve/lib/async.js:91:54
    at load (/usr/local/lib/node_modules/winstall/node_modules/installify/node_modules/resolve/lib/async.js:54:43)
    at /usr/local/lib/node_modules/winstall/node_modules/installify/node_modules/resolve/lib/async.js:60:22
    at /usr/local/lib/node_modules/winstall/node_modules/installify/node_modules/resolve/lib/async.js:16:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

```
❯ cat package.json | json main
index.js
```

```
❯ tree
.
├── index.js
├── package-lock.json
└── package.json
```

Despite the error, it appears to have worked! :tada:

```
❯ cat package.json | json dependencies
{
  "colors": "^1.1.2",
  "got": "^7.1.0"
}
```

**Comment by yoshuawuyts** [comment]
haha, lol - so we try and read the `package.json` anywhere up in the tree -
but guess it didn't find any? We should def catch that case haha :D

**Comment by zeke** [comment]
strange that it couldn't find it, considering it's in the same directory.

Are you back from vacation? :)

> [taking a vacation, back 31/07]

**Comment by yoshuawuyts** [comment]
Hahaha - just arrived back in Berlin; past midnight here - back tomorrow! :D
